# Generated by Django 3.1.7 on 2022-12-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('ticket_link', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gigs',
        ),
    ]
